projects:
  raamapp:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src\graphql
        graphQLApiId: 2yqa34xw2fdepb7gcwcsjvu7my
      endpoints:
        prod: >-
          https://44o7r2nhjnf2dhugturadwzuve.appsync-api.us-east-1.amazonaws.com/graphql
